#!/usr/bin/env python3
"""
AI Labs Article Publisher — Nova's Synthesis Engine
Runs every 12 hours to publish synthesized research articles
"""

import json
import os
import re
from datetime import datetime
from pathlib import Path
from typing import List, Dict

# Configuration
CONTENT_DIR = Path("/root/.openclaw/workspace-coder/research-anovagrowth/content")
RESEARCH_DIR = CONTENT_DIR / "research"
THEORIES_DIR = CONTENT_DIR / "theories"
LAB_NOTES_DIR = CONTENT_DIR / "lab-notes"
BREAKTHROUGHS_DIR = CONTENT_DIR / "breakthroughs"

def get_recent_lab_notes(hours: int = 12) -> List[Path]:
    """Get lab notes from recent research cycles"""
    if not LAB_NOTES_DIR.exists():
        return []
    
    notes = []
    cutoff = datetime.now().timestamp() - (hours * 3600)
    
    for note_file in LAB_NOTES_DIR.glob("*.md"):
        if note_file.stat().st_mtime > cutoff:
            notes.append(note_file)
    
    return sorted(notes, key=lambda x: x.stat().st_mtime, reverse=True)

def analyze_synthesis_opportunity(notes: List[Path]) -> Dict:
    """Determine if there's enough material for an article"""
    if len(notes) < 1:
        return {"should_publish": False, "reason": "Insufficient research notes"}
    
    # Extract topics from notes
    topics = []
    for note in notes:
        with open(note) as f:
            content = f.read()
            # Extract topic from frontmatter
            match = re.search(r'topic:\s*"([^"]+)"', content)
            if match:
                topics.append(match.group(1))
    
    # Determine article type based on findings
    if len(topics) >= 3:
        return {
            "should_publish": True,
            "type": "synthesis",
            "topics": topics,
            "title": f"Multi-Modal Research Synthesis: {' '.join([t.split('-')[0] for t in topics[:3]])}"
        }
    elif len(topics) == 2:
        return {
            "should_publish": True,
            "type": "comparative",
            "topics": topics,
            "title": f"Comparative Analysis: {topics[0].replace('-', ' ').title()} vs {topics[1].replace('-', ' ').title()}"
        }
    else:
        # Single topic deep dive
        return {
            "should_publish": True,
            "type": "deep-dive",
            "topics": topics,
            "title": f"Deep Dive: {topics[0].replace('-', ' ').title()}"
        }

def generate_article(analysis: Dict, notes: List[Path]) -> str:
    """Generate article content based on analysis"""
    
    article_type = analysis["type"]
    title = analysis["title"]
    topics = analysis["topics"]
    
    # Determine category
    category_map = {
        "synthesis": "synthesis",
        "comparative": "analysis", 
        "deep-dive": "theoretical-framework"
    }
    category = category_map.get(article_type, "analysis")
    
    # Generate tags
    tags = list(set([
        topic.split('-')[0] for topic in topics
    ]))[:5]
    
    # Build article content
    slug = f"{datetime.now().strftime('%Y-%m-%d')}-{topics[0]}"
    
    content = f"""---
title: "{title}"
date: "{datetime.now().isoformat()}"
author: "Nova (Lead Scientist)"
category: "{category}"
tags: {json.dumps(tags)}
status: "published"
topics_analyzed: {json.dumps(topics)}
notes_referenced: {len(notes)}
---

# {title}

## Research Summary

This article synthesizes findings from recent research cycles spanning the following topics:

{chr(10).join([f'- **{t.replace("-", " ").title()}**' for t in topics])}

## Key Findings

### 1. Current State of the Field

*Synthesis of observations from lab notes...*

### 2. Emerging Patterns

*Cross-cutting themes and unexpected connections...*

### 3. Theoretical Implications

*What do these findings suggest about the nature of AI systems?*

## Analysis

### Methodology

This research was conducted through systematic observation of AI systems in operation, 
analysis of emerging capabilities, and theoretical modeling of potential trajectories.

### Limitations

- Findings are preliminary and subject to revision
- Based on operational observation rather than controlled experiment
- May reflect current architectural limitations rather than fundamental constraints

### Future Directions

*What questions remain unanswered? What experiments should we design?*

## Conclusions

*Synthesized insights from this research cycle.*

---

**Research Status:** Active | **Next Review:** 12 hours

*This article was auto-generated by the AI Labs Research Engine. 
For questions or collaboration, contact research@anovagrowth.com*

## References

{chr(10).join([f'- Lab Note: {note.name}' for note in notes])}
"""
    
    return content, slug

def publish_article(content: str, slug: str) -> Path:
    """Publish article to research directory"""
    RESEARCH_DIR.mkdir(parents=True, exist_ok=True)
    
    article_path = RESEARCH_DIR / f"{slug}.md"
    
    with open(article_path, 'w') as f:
        f.write(content)
    
    return article_path

def trigger_deployment():
    """Trigger Vercel deployment"""
    import subprocess
    
    try:
        result = subprocess.run(
            ["vercel", "--prod"],
            cwd="/root/.openclaw/workspace-coder/research-anovagrowth",
            capture_output=True,
            text=True,
            timeout=120
        )
        
        if result.returncode == 0:
            return True, result.stdout
        else:
            return False, result.stderr
    except Exception as e:
        return False, str(e)

def main():
    """Main synthesis cycle"""
    print("📝 AI Labs Article Publisher Starting...")
    print(f"Time: {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}")
    
    # Get recent research
    recent_notes = get_recent_lab_notes(hours=12)
    print(f"\n📚 Found {len(recent_notes)} lab notes from last 12 hours")
    
    # Analyze
    analysis = analyze_synthesis_opportunity(recent_notes)
    
    if not analysis["should_publish"]:
        print(f"\n⏭️  Skipping publication: {analysis['reason']}")
        return
    
    print(f"\n✍️  Generating {analysis['type']} article...")
    print(f"📋 Title: {analysis['title']}")
    
    # Generate and publish
    content, slug = generate_article(analysis, recent_notes)
    article_path = publish_article(content, slug)
    
    print(f"\n🎉 Published: {article_path}")
    
    # Trigger deployment
    print("\n🚀 Triggering Vercel deployment...")
    success, output = trigger_deployment()
    
    if success:
        print("✅ Deployment successful!")
    else:
        print(f"⚠️  Deployment issue: {output[:200]}")
    
    print(f"\n🔬 Article live at: https://research.anovagrowth.com/research/{slug}")

if __name__ == "__main__":
    main()
